# Generated by Django 3.1.7 on 2021-04-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=100)),
                ('iamge', models.FilePathField(path='/img')),
            ],
        ),
    ]
