# Generated by Django 3.2 on 2021-05-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityes', '0002_person_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Person'},
        ),
    ]
