# Generated by Django 3.2.6 on 2021-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_with_orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'cat',
            },
        ),
    ]
