# Generated by Django 3.1.7 on 2021-03-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='valid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
