# Generated by Django 3.2.3 on 2021-06-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='per',
            new_name='pet',
        ),
    ]
