# Generated by Django 3.2.3 on 2021-05-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('name_path', models.CharField(max_length=150)),
                ('size', models.PositiveIntegerField()),
                ('time_access', models.DateTimeField()),
                ('modified', models.BooleanField(default=False)),
            ],
        ),
    ]
