# Generated by Django 3.2.3 on 2021-05-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_post_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
